public class PropellerSalesforce {
    public PropellerSalesforce() {

    }

    public static String mockAPIResponse(){
        return '{"id":"6064d79ab27d94000c668be0","createdDate":"2021-03-31T20:12:10.122+00:00","disease":"asthma","age":21,"birthDate":"2000-02-02", "email":"1617221524847@example.com","lastName":"Doe","firstName":"John","group":{"id":"5db31bf6a1ea140010742da9","name":"ph-us","displayName":"ph-US"},"language":"en-US","mailingAddress":{"street":"123 W. Main St.","city":"Madison","stateOrRegion":"Wisconsin","stateCode":"WI","postalCode":"55555","country":"US"}';
    }
}






